name: Workflow Staging
on:
  push:
      branches:
        - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up versioning
        run: echo "Last updated on `date`" > others/version.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: template.tex
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: pdf-result
          path: template.pdf
 